# Generated by Django 5.0.4 on 2024-05-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
